### ISSUE TITLE
Anonymise data

### ISSUE THREAD

**Issue by 240ch** [greenbird/xml-formatter-components#3]
Hi Thomas, I found this project through stackoverflow (http://stackoverflow.com/questions/23212313/cxf-logging-request-response-with-content-filtering) where you state that it's possible to "Anonymize of element and/or attribute contents". Unfortunately I didn't find the documentation or an example covering this topic. Could you please explain how to anonymise data, e.g. an xml attribute `<password>s3cure</password>` in a soap response? Is is also possible to filter maps, e.g. 
`<credentials>
<key>password</key>
<value>s3cure</value>
</credentials>`

**Comment by skjolber** [comment]
Are you using spring? If so see https://github.com/greenbird/xml-formatter-components/blob/master/spring.cheat.sheet.md. If not, see https://github.com/greenbird/xml-formatter-core for java API.

**Comment by skjolber** [comment]
Did you manage to properly anonymise your data?

**Comment by 240ch** [comment]
Hey, thanks for the links, I read through the pages. However, I ended up implementing something on my own due to more specific requirements.

**Comment by skjolber** [comment]
I understand - can I ask which additional features ended up in your solution?
